---
- name: replace nginx.conf
  copy:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: 0644
    backup: yes
  notify: restart nginx

- name: replace Nginx default.conf
  template:
    src: default.conf.j2
    dest: /etc/nginx/conf.d/default.conf
    owner: root
    group: root
    mode: 0644
    backup: yes
  notify: restart nginx

- name: change cache directory owner
  file:
    path: /var/cache/nginx/
    state: directory
    owner: nginx
  notify: restart nginx
