---
# http://nginx.org/en/linux_packages.html#RHEL-CentOS
- name: copy nginx.repo
  copy:
    src: nginx.repo
    dest: /etc/yum/repos.d/

- name: install nginx
  yum:
    name: nginx
    enablerepo: nginx-stable
    state: latest

- name: start and enable nginx service
  service:
    name: nginx.service
    state: started
    enabled: yes
