---
- name: install wp-cli
  get_url:
    url: https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
    dest: /usr/local/bin/wp
    mode: 0755

- name: update WP-CLI to the latest release
  command: /usr/local/bin/wp cli update

- name: create a symbolic link to enable sudo wp
  file:
    src: /usr/local/bin/wp
    dest: /usr/bin/wp
    owner: root
    group: root
    state: link
