---
- name: Provision oki2a24.com WordPress server
  hosts: web
  become: true
  roles:
    - role: swap
      tags: [never, first]
    - role: upgrade
      tags: [never, first]
    - role: common
      tags: common
    - role: php
      tags: php
    - role: php-fpm
      tags: php-fpm
    - role: nginx
      tags: nginx
    - role: cert
      tags: cert
    - role: mariadb
      tags: mariadb
    - role: wordpress
      tags: wordpress
