---
- name: generate an OpenSSL private key.
  openssl_privatekey:
    path: /etc/nginx/conf.d/privkey.pem

- name: generate an OpenSSL CSR.
  openssl_csr:
    path: /etc/nginx/conf.d/dummy.csr
    privatekey_path: /etc/nginx/conf.d/privkey.pem
    common_name: dummy

- name: generate a Self Signed OpenSSL certificate.
  openssl_certificate:
    path: /etc/nginx/conf.d/fullchain.pem
    privatekey_path: /etc/nginx/conf.d/privkey.pem
    csr_path: /etc/nginx/conf.d/dummy.csr
    provider: selfsigned
