---
- name: install MariaDB
  yum:
    name:
      - MariaDB-server
      - MariaDB-client
    enablerepo: mariadb
    state: latest

- name: STart and enable MariaDB Service
  service:
    name: mariadb
    state: started
    enabled: yes
